#!/bin/sh

set -eu

TAG=${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}

build_and_push() {
  image="$1"

  set -- \
    --platform linux/amd64,linux/arm64 \
    --tag "${image}:${TAG}"

  if [ -n "${CI_COMMIT_TAG:-}" ]; then
    set -- "$@" --tag "${image}:latest"
  fi

  docker buildx build \
    "$@" \
    --push .
}

docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
docker run --privileged --rm tonistiigi/binfmt --install arm64
docker buildx create --driver docker-container --name exporter-builder --use
docker buildx inspect --bootstrap

build_and_push "$CI_REGISTRY_IMAGE"

if [ -n "${CI_COMMIT_TAG:-}" ]; then
  docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_TOKEN"
  build_and_push alxrem/prometheus-logstash-exporter
fi
